<main>
    <div class="Box">
    	<div class="boxTitle">Términos y condiciones del servicio</div>
        <div class="boxContent">    	
            <div class="container">
				<p>Antes de registrarte en el servicio debes tener en cuenta que esto es un 'Habbo Retro', una copia de Habbo Hotel.<br/>{@name} usa <b>MasterCMS</b> creado por <a href="https://www.facebook.com/Denzel-Code-249037048887248" target="_new">Denzel Code</a>, jugar en un Habbo Retro no tiene peligro, pero se debe recordar que esto es <b>Ilegal</b>.<br/><br/>Este software tiene programado para encriptar las contraseñas de los usuarios con BlowFish por defecto, pero los dueños del servidor pueden cambiar la encriptación,<br/>por favor, asegúrese de que la siguiente palabra <b>Hola</b> a continuación sale encriptada: <b>hae8FuqAMGosJNJ.vJWJMG4NWNZ8KJ3hui</b>.<br/>Si no sale encriptada, quiere decir que los dueños pueden ver tu contraseña, así que... <b>¡Entre bajo su propio riesgo!</b><br/><br/>Tambien debes aceptar seguir las siguientes normas que tiene este Hotel.<br/><br/><b>Normas del Hotel:</b><br>Las normas se dividen en secciones que debes cumplir, son sencillos:<br><b><br>Respeto<br>Tolerancia<br>Script<br>Abuso</b><br><br>Cada seccion tiene reglas diferentes que deberas seguir. Para que puedas jugar limpiamente.<br><b><br>Respeto:</b><br><br>1- Respetar a todos los jugadores, sean como sean.<br>2- Respetar a los miembros Administrativos del Hotel, asi como a los Jugadores dentro.<br>3- Respetar las Creencias de cada quien dentro del Juego.<br>4- Respetar a los Habbo Guias.<br>5- Respetar el Chat y a las personas dentro de el.<br><b><br>Tolerancia:</b><br> <br>1- Tolerancia para los miembros Administrativos.<br>2- Tolerancia si en algun momento los miembros Administrativos se demoran para tus alertas.<br>3- Tolerancia al aceptar las reglas<br>4- Tolerancia Con los demas, Asi te evitas problemas.<br>5- Tolerancia con asuntos de primera mano<br><b><br>Script:</b><br><br>1- Recuerda, Los script estan totalmente prohibidos.<br>2- No uses programas Script dentro del Juego o seras <b>Eliminado</b> del Servidor.<br>3- Si tu problema causa problemas mayores, el equipo de Asistencia Tecnica hablara con tigo.<br>4- Los script a veces traen virus, Evitate problemas con tu ordenador.<br>5- Ten en cuenta que sabemos todo tipo de scripts, Asi que ninguno que intentes nos hara algun tipo de daño crítico. <br><b><br>Abuso:</b><br><br>1- Cuando se hacen las solicitudes para rango, No abuses con los miembros Administrativos.<br>2- Abusar con lo que te puedan brindar nuestros amigos staff.<br>3- Abusar del Equipo de Asistencia Tecnica o Ayuda.<br>4- Abusar o pasarse de la raya con las personas de tu sexo opuesto es motivo de baneo.<br>5- Recuerda Reportar a los Jugadores o inclusive a los Miembros <b>Administrativos</b> acerca de cualquier tipo de Rompimiento a las Normas. <br><br><br>Si necesitas mas Ayuda acerca de las Normas o algun otro tema puedes usar la Help Tool.<br/><b>NOTA: </b>Estos TÉRMINOS Y CONDICIONES estarán sujetos a cambios.</p>
            </div>
        </div>
    </div>
</main>